2022-01-10 13:28:28,975 INFO    MainThread:5796 [wandb_setup.py:_flush():71] setting env: {}
2022-01-10 13:28:28,975 INFO    MainThread:5796 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-10 13:28:28,976 INFO    MainThread:5796 [wandb_init.py:_log_setup():371] Logging user logs to C:\Users\zebra\.cookiecutters\mlops_day1\tests\wandb\run-20220110_132828-10nhpkkl\logs\debug.log
2022-01-10 13:28:28,976 INFO    MainThread:5796 [wandb_init.py:_log_setup():372] Logging internal logs to C:\Users\zebra\.cookiecutters\mlops_day1\tests\wandb\run-20220110_132828-10nhpkkl\logs\debug-internal.log
2022-01-10 13:28:28,976 INFO    MainThread:5796 [wandb_init.py:init():404] calling init triggers
2022-01-10 13:28:28,976 INFO    MainThread:5796 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-01-10 13:28:28,976 INFO    MainThread:5796 [wandb_init.py:init():460] starting backend
2022-01-10 13:28:28,977 INFO    MainThread:5796 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn, using: spawn
2022-01-10 13:28:28,982 INFO    MainThread:5796 [backend.py:ensure_launched():216] starting backend process...
2022-01-10 13:28:29,133 INFO    MainThread:5796 [backend.py:ensure_launched():221] started backend process with pid: 15444
2022-01-10 13:28:29,134 INFO    MainThread:5796 [wandb_init.py:init():469] backend started and connected
2022-01-10 13:28:29,134 INFO    MainThread:5796 [wandb_init.py:init():533] updated telemetry
2022-01-10 13:28:29,294 INFO    MainThread:5796 [wandb_init.py:init():563] communicating current version
2022-01-10 13:28:30,382 INFO    MainThread:5796 [wandb_init.py:init():568] got version response 
2022-01-10 13:28:30,382 INFO    MainThread:5796 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-10 13:28:30,720 INFO    MainThread:5796 [wandb_init.py:init():606] starting run threads in backend
2022-01-10 13:28:30,976 INFO    MainThread:5796 [wandb_run.py:_console_start():1810] atexit reg
2022-01-10 13:28:30,977 INFO    MainThread:5796 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-01-10 13:28:30,977 INFO    MainThread:5796 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-01-10 13:28:30,980 INFO    MainThread:5796 [wandb_run.py:_redirect():1745] Redirects installed.
2022-01-10 13:28:30,980 INFO    MainThread:5796 [wandb_init.py:init():633] run started, returning control to user process
2022-01-10 13:28:31,995 INFO    MainThread:5796 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-01-10 13:28:31,996 INFO    MainThread:5796 [wandb_run.py:_restore():1752] restore
2022-01-10 13:28:32,520 INFO    MainThread:5796 [wandb_run.py:_restore():1752] restore
2022-01-10 13:28:35,066 ERROR   MainThread:5796 [wandb_run.py:_atexit_cleanup():1798] Problem finishing run
Traceback (most recent call last):
  File "C:\Users\zebra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\wandb\sdk\wandb_run.py", line 1788, in _atexit_cleanup
    self._on_finish()
  File "C:\Users\zebra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\wandb\sdk\wandb_run.py", line 1958, in _on_finish
    print("")
ValueError: I/O operation on closed file.
